# Site settings
title: Rex Posadas
email: rexposadas@yahoo.com
description: "Go + Video Games = Life"
baseurl: ""
username: "rexposadas"
url: "http://rexposadas.com"

# Build settings
markdown: kramdown
permalink: pretty
